# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Mingo Hagen"
tagline: ""
description: "Follow <a href=\"https://micro.blog/mjhagen\">@mjhagen on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/mjhagen\">@mjhagen on Micro.blog</a>."
baseurl: ""
url: "https://mjhagen.micro.blog"
markdown: "kramdown"
username: "mjhagen"
microblog_user: "mjhagen"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Mingo Hagen"
name: "Mingo Hagen"
gravatar_hash: "19cd932b44107c045bc0985a3408e1a1"
avatar: "https://micro.blog/mjhagen/avatar.jpg"
full_name: "Mingo Hagen"
bio: ""
twitter_username: "mjhagen"
github_username: "mjhagen"
instagram_username: "mjhagen"
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "4438"
gems: ["jekyll-paginate"]
itunes_description: "Web dev from Amsterdam"
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Mingo Hagen"
itunes_email: ""
podcast: false